version: "3.9"

services:

  postgres:
    image: ${REGISTRY}/url-shortener-postgres:${IMAGE_TAG}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - postgres_password
    networks:
      - url-shortener-net
    deploy:
      placement:
        constraints: [ node.labels.frontend == frontend ]
      endpoint_mode: dnsrr

  url-shortener:
    image: ${REGISTRY}/url-shortener:${IMAGE_TAG}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
      URL_SHORTENER_STORE: pg
    secrets:
      - postgres_password
    networks:
      - url-shortener-net
      - traefik-public
    deploy:
      placement:
        constraints: [ node.labels.frontend == frontend ]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.url-shortener.rule=Host(`url.svodd.ru`)
        - traefik.http.services.url-shortener.loadBalancer.server.port=8000
        - traefik.http.routers.url-shortener.entryPoints=https
        - traefik.http.routers.url-shortener.tls=true
        - traefik.http.routers.url-shortener.tls.certResolver=letsEncrypt
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE}

volumes:
  postgres:

networks:
  traefik-public:
    external: true
  url-shortener-net:
