version: "3.9"

services:

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    restart: always
    networks:
      - url-shortener-net

  postgres:
    image: localhost:5000/postgres:latest
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - "54325:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: short_links
    secrets:
      - postgres_password
    networks:
      - url-shortener-net

  url-shortener:
    image: localhost:5000/url-shortener:latest
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: short_links
      URL_SHORTENER_STORE: pg
    secrets:
      - postgres_password
    depends_on:
      - registry
      - postgres
    networks:
      - url-shortener-net

secrets:
  postgres_password:
    file: ./docker/development/secrets/postgres_password


volumes:
  postgres:

networks:
  url-shortener-net:
